language: node_js
node_js:
  - 7
services:
  - docker

git:
  submodules: false

install:
- docker pull critzel/test
- docker run -d -p critzel/test echo $customVar
- docker ps -a

before_script:
  - npm install -g gulp-cli
  
script:
  - echo 'Hello World!'
